/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTutorRouteImport } from './routes/api.tutor'
import { Route as ApiSpeakRouteImport } from './routes/api.speak'
import { Route as ApiDiscussionRouteImport } from './routes/api.discussion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTutorRoute = ApiTutorRouteImport.update({
  id: '/api/tutor',
  path: '/api/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscussionRoute = ApiDiscussionRouteImport.update({
  id: '/api/discussion',
  path: '/api/discussion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/discussion': typeof ApiDiscussionRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/discussion': typeof ApiDiscussionRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/discussion': typeof ApiDiscussionRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/tutor': typeof ApiTutorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/discussion' | '/api/speak' | '/api/tutor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/discussion' | '/api/speak' | '/api/tutor'
  id: '__root__' | '/' | '/api/discussion' | '/api/speak' | '/api/tutor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDiscussionRoute: typeof ApiDiscussionRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiTutorRoute: typeof ApiTutorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tutor': {
      id: '/api/tutor'
      path: '/api/tutor'
      fullPath: '/api/tutor'
      preLoaderRoute: typeof ApiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discussion': {
      id: '/api/discussion'
      path: '/api/discussion'
      fullPath: '/api/discussion'
      preLoaderRoute: typeof ApiDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDiscussionRoute: ApiDiscussionRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiTutorRoute: ApiTutorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
